#Requires -Version 5.1
[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$base='http://127.0.0.1:8096'
$serverId='5ae656ad8fc948f38e1ac1d5a6769aa5'
$known=[ordered]@{coolyo='2D994DBA-B8C7-44C8-8D34-7D85716B2EBC';movies='64F6DF5C-78B5-4DFE-B0FF-7295CBFB3A5A'}
function Add-Candidate([System.Collections.Generic.HashSet[string]]$Set,[string]$Value){if([string]::IsNullOrWhiteSpace($Value)){return};$v=$Value.Trim().Trim('"').Trim("'");if($v.Length -ge 20 -and $v.Length -le 256 -and $v -match '^[A-Za-z0-9._-]+$'){[void]$Set.Add($v)}}
function Scan-Buffer([System.Collections.Generic.HashSet[string]]$Set,[byte[]]$buf){foreach($enc in @([Text.Encoding]::UTF8,[Text.Encoding]::Unicode)){try{$text=$enc.GetString($buf)}catch{continue};$interesting=($text -match '(?i)jellyfin|AccessToken|192\.168\.50\.94|'+$serverId);foreach($rx in @('(?i)AccessToken[^A-Za-z0-9._-]{0,96}([A-Za-z0-9._-]{20,256})','(?i)accessToken[^A-Za-z0-9._-]{0,96}([A-Za-z0-9._-]{20,256})','(?i)X-Emby-Token[^A-Za-z0-9._-]{0,96}([A-Za-z0-9._-]{20,256})')){foreach($m in [regex]::Matches($text,$rx)){Add-Candidate $Set $m.Groups[1].Value}};if($interesting){foreach($m in [regex]::Matches($text,'(?i)(?<![A-Fa-f0-9])[A-Fa-f0-9]{32}(?![A-Fa-f0-9])')){Add-Candidate $Set $m.Value}}}}
Write-Output 'AFZ_JELLYFIN_BROWSER_LIVE_VIEWS_AUDIT_V3';Write-Output ('TIME='+(Get-Date -Format o));Write-Output 'READ_ONLY=true';Write-Output 'SECRET_EXPOSED=false'
$candidates=New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal)
$roots=@('C:\Users\Faiz\AppData\Local\Google\Chrome\User Data','C:\Users\Faiz\AppData\Local\Microsoft\Edge\User Data')
$fileCount=0;$profileCount=0;$indexedCount=0
foreach($root in $roots){if(-not(Test-Path -LiteralPath $root -PathType Container)){continue};Write-Output ('BROWSER_ROOT|path='+$root);$profiles=@(Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue|Where-Object {$_.Name -eq 'Default' -or $_.Name -like 'Profile *'});$profileCount+=$profiles.Count;foreach($profile in $profiles){$dirs=New-Object System.Collections.Generic.List[string];foreach($rel in @('Local Storage\leveldb','Session Storage','IndexedDB')){$p=Join-Path $profile.FullName $rel;if(Test-Path -LiteralPath $p -PathType Container){[void]$dirs.Add($p)}};foreach($dir in $dirs){$files=@(Get-ChildItem -LiteralPath $dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object {$_.Extension -in @('.ldb','.log')});if($dir -like '*IndexedDB*'){$indexedCount+=$files.Count};foreach($f in $files){$fileCount++;try{$fs=New-Object IO.FileStream($f.FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite);try{$buf=New-Object byte[] $fs.Length;[void]$fs.Read($buf,0,$buf.Length)}finally{$fs.Dispose()};Scan-Buffer $candidates $buf}catch{}}}}}
Write-Output ('BROWSER_PROFILES_SCANNED='+$profileCount);Write-Output ('BROWSER_FILES_SCANNED='+$fileCount);Write-Output ('INDEXEDDB_FILES_SCANNED='+$indexedCount);Write-Output ('TOKEN_CANDIDATES='+$candidates.Count)
$success=0;$unique=New-Object 'System.Collections.Generic.HashSet[string]'
foreach($token in $candidates){foreach($entry in $known.GetEnumerator()){try{$r=Invoke-RestMethod -Uri ($base+'/Users/'+$entry.Value+'/Views?IncludeExternalContent=true') -Headers @{'X-Emby-Token'=$token} -TimeoutSec 6;$names=@($r.Items|ForEach-Object {[string]$_.Name});$k=$entry.Key+'|'+($names -join '||');if($unique.Add($k)){Write-Output ('LIVE_VIEWS|user='+$entry.Key+'|count='+$names.Count+'|names='+($names -join ' || '))};$success++}catch{}}}
Write-Output ('LIVE_VIEW_SUCCESSES='+$success);Write-Output 'SECRET_EXPOSED=false';Write-Output 'AUDIT_STATUS=PASS'
